### ISSUE TITLE
message: #warning "localeconv not available"

### ISSUE THREAD

**Issue by raulvigueras** [mfbonfigli/gocesiumtiler#29]
I have tried to implement numerous times but the message is always the same. How can I solve this problem? Apparently it has to do with the proj4 library

root@MSI:/home/rvp/gocesiumtiler# export CGO_LDFLAGS="-g -O2 -lm"
root@MSI:/home/rvp/gocesiumtiler# go build
go: downloading github.com/xeonx/proj4 v0.0.0-20151223112312-c52078bad901
go: extracting github.com/xeonx/proj4 v0.0.0-20151223112312-c52078bad901
go: downloading github.com/xeonx/geom v0.0.0-20151223130215-76a21efc1ce4
go: extracting github.com/xeonx/geom v0.0.0-20151223130215-76a21efc1ce4
go: finding github.com/xeonx/proj4 v0.0.0-20151223112312-c52078bad901
go: finding github.com/xeonx/geom v0.0.0-20151223130215-76a21efc1ce4
github.com/xeonx/proj4
pj_strtod.c: In function ‘pj_replace_point_by_locale_point’:
pj_strtod.c:79:2: warning: #warning "localeconv not available" [-Wcpp]
   79 | #warning "localeconv not available"
      |  ^~~~~~~

**Comment by pvictorino** [comment]
Try to install pyproj, proj4 to resolve this:
conda install proj4
conda install pyproj
The binary file will be on path

**Comment by mattijn** [comment]
Same error here. This is the traceback when I run the tests:
```cmd
(datafusiontools) jupyter-hoek@MMPC:/opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler$ export CGO_LDFLAGS="-g -O2 -lm"
(datafusiontools) jupyter-hoek@MMPC:/opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler$ go test ./test/... -v
# github.com/xeonx/proj4
pj_strtod.c: In function 'pj_replace_point_by_locale_point':
pj_strtod.c:79:2: warning: #warning "localeconv not available" [-Wcpp]
   79 | #warning "localeconv not available"
      |  ^~~~~~~
=== RUN   TestBufferedElevationConverter
--- PASS: TestBufferedElevationConverter (0.01s)
=== RUN   TestSinglePointElevationConverter
--- PASS: TestSinglePointElevationConverter (0.01s)
=== RUN   TestGeoidElevationCorrector
--- PASS: TestGeoidElevationCorrector (0.00s)
=== RUN   TestGetEllipsoidToGeoidZOffsetFrom32633Correct
--- PASS: TestGetEllipsoidToGeoidZOffsetFrom32633Correct (0.00s)
=== RUN   TestGetEllipsoidToGeoidZOffsetFrom4326Correct
--- PASS: TestGetEllipsoidToGeoidZOffsetFrom4326Correct (0.00s)
=== RUN   TestGridNodeAddDataPointSinglePoint
--- PASS: TestGridNodeAddDataPointSinglePoint (0.00s)
=== RUN   TestGridNodeAddDataPointMultiplePoints
--- PASS: TestGridNodeAddDataPointMultiplePoints (0.00s)
=== RUN   TestGridNodeGetInternalSrid
--- PASS: TestGridNodeGetInternalSrid (0.00s)
=== RUN   TestGridNodeGetIsRootTrue
--- PASS: TestGridNodeGetIsRootTrue (0.00s)
=== RUN   TestGridNodeGetIsRootFalse
--- PASS: TestGridNodeGetIsRootFalse (0.00s)
=== RUN   TestGridNodeGetBoundingBoxRegion
--- PASS: TestGridNodeGetBoundingBoxRegion (0.00s)
=== RUN   TestGridNodeGetChildren
--- PASS: TestGridNodeGetChildren (0.00s)
=== RUN   TestGridNodeGetPoints
--- PASS: TestGridNodeGetPoints (0.00s)
=== RUN   TestGridNodeGetTotalNumberOfPoints
--- PASS: TestGridNodeGetTotalNumberOfPoints (0.00s)
=== RUN   TestGridNodeGetNumberOfPoints
--- PASS: TestGridNodeGetNumberOfPoints (0.00s)
=== RUN   TestGridNodeIsLeaf
--- PASS: TestGridNodeIsLeaf (0.00s)
=== RUN   TestGridNodeIsInitialized
--- PASS: TestGridNodeIsInitialized (0.00s)
=== RUN   TestGridNodeComputeGeometricError
--- PASS: TestGridNodeComputeGeometricError (0.00s)
=== RUN   TestRootGridNodeComputeGeometricError
--- PASS: TestRootGridNodeComputeGeometricError (0.00s)
=== RUN   TestGridNodeGetParent
--- PASS: TestGridNodeGetParent (0.00s)
=== RUN   TestTreeAddPointSuccess
--- PASS: TestTreeAddPointSuccess (0.00s)
=== RUN   TestTreeBuildSuccess
--- PASS: TestTreeBuildSuccess (0.00s)
=== RUN   TestGetRootNode
--- PASS: TestGetRootNode (0.00s)
=== RUN   TestElevationIsAdded
--- PASS: TestElevationIsAdded (0.00s)
=== RUN   TestElevationIsSubtracted
--- PASS: TestElevationIsSubtracted (0.00s)
=== RUN   TestElevationIsLeftUnchanged
--- PASS: TestElevationIsLeftUnchanged (0.00s)
=== RUN   TestElevationCorrectionsAreSummed
--- PASS: TestElevationCorrectionsAreSummed (0.00s)
=== RUN   TestConvertsCoordinate
    proj4_coordinate_converter_test.go:47: Expected X within -121.14053500 ± 0.00000050, got X:-121.14043589
    proj4_coordinate_converter_test.go:56: Expected Y within 44.65872800 ± 0.00000050, got Y:44.65872334
--- FAIL: TestConvertsCoordinate (0.00s)
=== RUN   TestConvertsFromUnknownSridReturnsError
--- PASS: TestConvertsFromUnknownSridReturnsError (0.00s)
=== RUN   TestConvertsToUnknownSridReturnsError
--- PASS: TestConvertsToUnknownSridReturnsError (0.00s)
=== RUN   TestConvertsFrom4326toWGS84Cartesian
--- PASS: TestConvertsFrom4326toWGS84Cartesian (0.00s)
=== RUN   TestConvert326322DBoundingboxToWGS84Region
--- PASS: TestConvert326322DBoundingboxToWGS84Region (0.00s)
=== RUN   TestSequentialLoaderAddPoint
--- PASS: TestSequentialLoaderAddPoint (0.00s)
=== RUN   TestSequentialLoaderGetNext
--- PASS: TestSequentialLoaderGetNext (0.00s)
=== RUN   TestSequentialLoaderGetBounds
--- PASS: TestSequentialLoaderGetBounds (0.00s)
=== RUN   TestAlgorithmManagerReturnsGridTree
--- PASS: TestAlgorithmManagerReturnsGridTree (0.01s)
=== RUN   TestAlgorithmManagerReturnsRandomTree
--- PASS: TestAlgorithmManagerReturnsRandomTree (0.01s)
=== RUN   TestAlgorithmManagerReturnsRandomBoxTree
--- PASS: TestAlgorithmManagerReturnsRandomBoxTree (0.01s)
=== RUN   TestAlgorithmManagerReturnsProj4CoordinateConverter
--- PASS: TestAlgorithmManagerReturnsProj4CoordinateConverter (0.01s)
=== RUN   TestAlgorithmManagerReturnsOffsetElevationCorrector
--- PASS: TestAlgorithmManagerReturnsOffsetElevationCorrector (0.01s)
=== RUN   TestAlgorithmManagerReturnsGeoidElevationCorrector
--- PASS: TestAlgorithmManagerReturnsGeoidElevationCorrector (0.01s)
=== RUN   TestConsumerSinglePointNoChildrenEPSG4326
panic: test timed out after 10m0s

goroutine 104 [running]:
testing.(*M).startAlarm.func1()
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:2029 +0x8e
created by time.goFunc
        /opt/tljh/user/envs/datafusiontools/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000103040, {0x5d1ccd?, 0x4d87a5?}, 0x5d63b8)
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0001a4150?)
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc000103040, 0xc000077cd8)
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0000b2000?, {0x6e0e20, 0x5a, 0x5a}, {0x7fec34512108?, 0x40?, 0x6fafc0?})
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0000b2000)
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1719 +0x5d9
main.main()
        _testmain.go:227 +0x1aa

goroutine 146 [chan send, 10 minutes]:
github.com/mfbonfigli/gocesiumtiler/internal/io.(*StandardConsumer).Consume(0xc000065fd0?, 0x4d98ea?, 0xc000a94680?, 0x5d63b8?)
        /opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler/internal/io/std_consumer.go:58 +0x7e
created by github.com/mfbonfigli/gocesiumtiler/test/unit.TestConsumerSinglePointNoChildrenEPSG4326
        /opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler/test/unit/std_consumer_test.go:58 +0x51d

goroutine 129 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc000075e40?)
        /opt/tljh/user/envs/datafusiontools/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000d16060?)
        /opt/tljh/user/envs/datafusiontools/go/src/sync/waitgroup.go:136 +0x52
github.com/mfbonfigli/gocesiumtiler/test/unit.TestConsumerSinglePointNoChildrenEPSG4326(0xc000a94680)
        /opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler/test/unit/std_consumer_test.go:67 +0x55f
testing.tRunner(0xc000a94680, 0x5d63b8)
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /opt/tljh/user/envs/datafusiontools/go/src/testing/testing.go:1486 +0x35f
FAIL    github.com/mfbonfigli/gocesiumtiler/test/unit   600.113s
FAIL
(datafusiontools) jupyter-hoek@MMPC:/opt/tljh/user/envs/datafusiontools/lib/python3.9/site-packages/DataFusionTools/visualisation/gocesiumtiler$ 
```

**Comment by mfbonfigli** [comment]
Hi, I'm not quite sure what could be causing it. I can share my build setup details on both windows and linux.

On Windows I use MinGW to compile the C code with `cgo`. I download it from https://winlibs.com/. You can use the version `GCC 13.1.0 + LLVM/Clang/LLD/LLDB 16.0.2 + MinGW-w64 11.0.0 (UCRT)` which I can confirm it works on my system. Once unzipped just reference the bin library in the `PATH` environment variable. 

On Linux the builds are running on Amazon Linux 2, prior to building I install some dependencies to build the C code via `yum -y install make glibc-devel gcc patch`. Other than this I set the environment variable `CGO_LDFLAGS` to  `-g -O2 -lm`

Hope this helps figuring out what's happening.

**Comment by yadunandan6176** [comment]
Hi, 
I am facing the same issue on Ubuntu 20.04, 
I have also set the environment variable `CGO_LDFLAGS` to `-g -02 -lm` as per the installation document for linux. 
Here is the screenshot of the warning:
`ThinkPad-E14-Gen-2:~/las_to_3dtiles/gocesiumtiler$ go build
# github.com/xeonx/proj4
pj_strtod.c: In function ‘pj_replace_point_by_locale_point’:
pj_strtod.c:79:2: warning: #warning "localeconv not available" [-Wcpp]
   79 | #warning "localeconv not available"
      |  ^~~~~~~
`
I tried installing glibc-devel from apt package manager. It was unable to find the package.

**Comment by mfbonfigli** [comment]
Thanks for the info. I definitely had this building on Ubuntu too in the
past, I will take a look at it as soon as possible and post here the
dependencies required for it to compile properly

Il Mar 23 Mag 2023, 13:47 yadunandan6176 ***@***.***> ha
scritto:

**Comment by mfbonfigli** [comment]
Hello, 

I just tried building the code from a fresh Ubuntu 22.04 install and it worked properly:

First  I downloaded the repo and installed the build tools (*note that on ubuntu I used the "**build-essential**" yum package*):
```
wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
sudo apt update
sudo apt get build-essential
git clone https://github.com/mfbonfigli/gocesiumtiler.git
```

Then I build it and run the test. The warnings are still shown but they don't impact the functionality or the build process:
```
ubuntu@ip-172-31-42-78:~/documents/gocesiumtiler$ go env CGO_ENABLED
1
ubuntu@ip-172-31-42-78:~/documents/gocesiumtiler$ export CGO_LDFLAGS="-g -O2 -lm"
ubuntu@ip-172-31-42-78:~/documents/gocesiumtiler$ go build
go: downloading github.com/xeonx/proj4 v0.0.0-20151223112312-c52078bad901
go: downloading github.com/xeonx/geom v0.0.0-20151223130215-76a21efc1ce4
# github.com/xeonx/proj4
pj_strtod.c: In function ‘pj_replace_point_by_locale_point’:
pj_strtod.c:79:2: warning: #warning "localeconv not available" [-Wcpp]
   79 | #warning "localeconv not available"
      |  ^~~~~~~
ubuntu@ip-172-31-42-78:~/documents/gocesiumtiler$ go test ./test/... -v
# github.com/xeonx/proj4
pj_strtod.c: In function ‘pj_replace_point_by_locale_point’:
pj_strtod.c:79:2: warning: #warning "localeconv not available" [-Wcpp]
   79 | #warning "localeconv not available"
      |  ^~~~~~~
=== RUN   TestBufferedElevationConverter
--- PASS: TestBufferedElevationConverter (0.02s)
=== RUN   TestSinglePointElevationConverter
--- PASS: TestSinglePointElevationConverter (0.02s)
=== RUN   TestGeoidElevationCorrector
--- PASS: TestGeoidElevationCorrector (0.00s)
=== RUN   TestGetEllipsoidToGeoidZOffsetFrom32633Correct
--- PASS: TestGetEllipsoidToGeoidZOffsetFrom32633Correct (0.00s)
=== RUN   TestGetEllipsoidToGeoidZOffsetFrom4326Correct
--- PASS: TestGetEllipsoidToGeoidZOffsetFrom4326Correct (0.00s)
=== RUN   TestGridNodeAddDataPointSinglePoint
--- PASS: TestGridNodeAddDataPointSinglePoint (0.00s)
=== RUN   TestGridNodeAddDataPointMultiplePoints
--- PASS: TestGridNodeAddDataPointMultiplePoints (0.00s)
=== RUN   TestGridNodeGetInternalSrid
--- PASS: TestGridNodeGetInternalSrid (0.00s)
=== RUN   TestGridNodeGetIsRootTrue
--- PASS: TestGridNodeGetIsRootTrue (0.00s)
=== RUN   TestGridNodeGetIsRootFalse
--- PASS: TestGridNodeGetIsRootFalse (0.00s)
=== RUN   TestGridNodeGetBoundingBoxRegion
--- PASS: TestGridNodeGetBoundingBoxRegion (0.00s)
=== RUN   TestGridNodeGetChildren
--- PASS: TestGridNodeGetChildren (0.00s)
=== RUN   TestGridNodeGetPoints
--- PASS: TestGridNodeGetPoints (0.00s)
=== RUN   TestGridNodeGetTotalNumberOfPoints
--- PASS: TestGridNodeGetTotalNumberOfPoints (0.00s)
=== RUN   TestGridNodeGetNumberOfPoints
--- PASS: TestGridNodeGetNumberOfPoints (0.00s)
=== RUN   TestGridNodeIsLeaf
--- PASS: TestGridNodeIsLeaf (0.00s)
=== RUN   TestGridNodeIsInitialized
--- PASS: TestGridNodeIsInitialized (0.00s)
=== RUN   TestGridNodeComputeGeometricError
--- PASS: TestGridNodeComputeGeometricError (0.00s)
=== RUN   TestRootGridNodeComputeGeometricError
--- PASS: TestRootGridNodeComputeGeometricError (0.00s)
=== RUN   TestGridNodeGetParent
--- PASS: TestGridNodeGetParent (0.00s)
=== RUN   TestTreeAddPointSuccess
--- PASS: TestTreeAddPointSuccess (0.00s)
=== RUN   TestTreeBuildSuccess
--- PASS: TestTreeBuildSuccess (0.00s)
=== RUN   TestGetRootNode
--- PASS: TestGetRootNode (0.00s)
=== RUN   TestElevationIsAdded
--- PASS: TestElevationIsAdded (0.00s)
=== RUN   TestElevationIsSubtracted
--- PASS: TestElevationIsSubtracted (0.00s)
=== RUN   TestElevationIsLeftUnchanged
--- PASS: TestElevationIsLeftUnchanged (0.00s)
=== RUN   TestElevationCorrectionsAreSummed
--- PASS: TestElevationCorrectionsAreSummed (0.00s)
=== RUN   TestConvertsCoordinate
--- PASS: TestConvertsCoordinate (0.00s)
=== RUN   TestConvertsFromUnknownSridReturnsError
--- PASS: TestConvertsFromUnknownSridReturnsError (0.00s)
=== RUN   TestConvertsToUnknownSridReturnsError
--- PASS: TestConvertsToUnknownSridReturnsError (0.00s)
=== RUN   TestConvertsFrom4326toWGS84Cartesian
--- PASS: TestConvertsFrom4326toWGS84Cartesian (0.00s)
=== RUN   TestConvert326322DBoundingboxToWGS84Region
--- PASS: TestConvert326322DBoundingboxToWGS84Region (0.00s)
=== RUN   TestSequentialLoaderAddPoint
--- PASS: TestSequentialLoaderAddPoint (0.00s)
=== RUN   TestSequentialLoaderGetNext
--- PASS: TestSequentialLoaderGetNext (0.00s)
=== RUN   TestSequentialLoaderGetBounds
--- PASS: TestSequentialLoaderGetBounds (0.00s)
=== RUN   TestAlgorithmManagerReturnsGridTree
--- PASS: TestAlgorithmManagerReturnsGridTree (0.02s)
=== RUN   TestAlgorithmManagerReturnsRandomTree
--- PASS: TestAlgorithmManagerReturnsRandomTree (0.01s)
=== RUN   TestAlgorithmManagerReturnsRandomBoxTree
--- PASS: TestAlgorithmManagerReturnsRandomBoxTree (0.01s)
=== RUN   TestAlgorithmManagerReturnsProj4CoordinateConverter
--- PASS: TestAlgorithmManagerReturnsProj4CoordinateConverter (0.02s)
=== RUN   TestAlgorithmManagerReturnsOffsetElevationCorrector
--- PASS: TestAlgorithmManagerReturnsOffsetElevationCorrector (0.02s)
=== RUN   TestAlgorithmManagerReturnsGeoidElevationCorrector
--- PASS: TestAlgorithmManagerReturnsGeoidElevationCorrector (0.02s)
=== RUN   TestConsumerSinglePointNoChildrenEPSG4326
--- PASS: TestConsumerSinglePointNoChildrenEPSG4326 (0.00s)
=== RUN   TestConsumerSinglePointNoChildrenEPSG32633
--- PASS: TestConsumerSinglePointNoChildrenEPSG32633 (0.00s)
=== RUN   TestConsumerOneChild
--- PASS: TestConsumerOneChild (0.00s)
=== RUN   TestConsumerOneChildRefineModeReplace
--- PASS: TestConsumerOneChildRefineModeReplace (0.00s)
=== RUN   TestProducerInjectsWorkUnits
--- PASS: TestProducerInjectsWorkUnits (0.00s)
=== RUN   TestConvertIntToByteArrayZero
--- PASS: TestConvertIntToByteArrayZero (0.00s)
=== RUN   TestConvertTruncateFloat64ToFloat32ByteArray
--- PASS: TestConvertTruncateFloat64ToFloat32ByteArray (0.00s)
=== RUN   TestBoundingBox
--- PASS: TestBoundingBox (0.00s)
=== RUN   TestBoundingBoxFromParent
--- PASS: TestBoundingBoxFromParent (0.00s)
=== RUN   TestGetWGS84Volume
--- PASS: TestGetWGS84Volume (0.00s)
=== RUN   TestInputFlagIsParsed
--- PASS: TestInputFlagIsParsed (0.00s)
=== RUN   TestIFlagIsParsed
--- PASS: TestIFlagIsParsed (0.00s)
=== RUN   TestOutputFlagIsParsed
--- PASS: TestOutputFlagIsParsed (0.00s)
=== RUN   TestOFlagIsParsed
--- PASS: TestOFlagIsParsed (0.00s)
=== RUN   TestSridFlagIsParsed
--- PASS: TestSridFlagIsParsed (0.00s)
=== RUN   TestEFlagIsParsed
--- PASS: TestEFlagIsParsed (0.00s)
=== RUN   TestSridFlagDefaultIs4326
--- PASS: TestSridFlagDefaultIs4326 (0.00s)
=== RUN   TestZOffsetFlagIsParsed
--- PASS: TestZOffsetFlagIsParsed (0.00s)
=== RUN   TestZFlagIsParsed
--- PASS: TestZFlagIsParsed (0.00s)
=== RUN   TestZOffsetFlagDefaultIsZero
--- PASS: TestZOffsetFlagDefaultIsZero (0.00s)
=== RUN   TestMaxPtsFlagIsParsed
--- PASS: TestMaxPtsFlagIsParsed (0.00s)
=== RUN   TestMFlagIsParsed
--- PASS: TestMFlagIsParsed (0.00s)
=== RUN   TestMaxPtsFlagDefaultIs50000
--- PASS: TestMaxPtsFlagDefaultIs50000 (0.00s)
=== RUN   TestGeoidFlagIsParsed
--- PASS: TestGeoidFlagIsParsed (0.00s)
=== RUN   TestGFlagIsParsed
--- PASS: TestGFlagIsParsed (0.00s)
=== RUN   TestGeoidFlagDefaultIsFalse
--- PASS: TestGeoidFlagDefaultIsFalse (0.00s)
=== RUN   TestFolderProcessingFlagIsParsed
--- PASS: TestFolderProcessingFlagIsParsed (0.00s)
=== RUN   TestFFlagIsParsed
--- PASS: TestFFlagIsParsed (0.00s)
=== RUN   TestFolderProcessingDefaultIsFalse
--- PASS: TestFolderProcessingDefaultIsFalse (0.00s)
=== RUN   TestRecursiveFolderProcessingFlagIsParsed
--- PASS: TestRecursiveFolderProcessingFlagIsParsed (0.00s)
=== RUN   TestRFlagIsParsed
--- PASS: TestRFlagIsParsed (0.00s)
=== RUN   TestRecursiveFolderProcessingDefaultIsFalse
--- PASS: TestRecursiveFolderProcessingDefaultIsFalse (0.00s)
=== RUN   TestSilentFlagIsParsed
--- PASS: TestSilentFlagIsParsed (0.00s)
=== RUN   TestSFlagIsParsed
--- PASS: TestSFlagIsParsed (0.00s)
=== RUN   TestSilentFlagDefaultIsFalse
--- PASS: TestSilentFlagDefaultIsFalse (0.00s)
=== RUN   TestLogTimestampFlagIsParsed
--- PASS: TestLogTimestampFlagIsParsed (0.00s)
=== RUN   TestTFlagIsParsed
--- PASS: TestTFlagIsParsed (0.00s)
=== RUN   TestLogTimestampFlagDefaultIsFalse
--- PASS: TestLogTimestampFlagDefaultIsFalse (0.00s)
=== RUN   TestAlgorithmFlagIsParsed
--- PASS: TestAlgorithmFlagIsParsed (0.00s)
=== RUN   TestAlgorithmDefaultIsGrid
--- PASS: TestAlgorithmDefaultIsGrid (0.00s)
=== RUN   TestGridMaxSizeFlagIsParsed
--- PASS: TestGridMaxSizeFlagIsParsed (0.00s)
=== RUN   TestGridMaxSizeFlagDefaultIs5m
--- PASS: TestGridMaxSizeFlagDefaultIs5m (0.00s)
=== RUN   TestGridMinSizeFlagIsParsed
--- PASS: TestGridMinSizeFlagIsParsed (0.00s)
=== RUN   TestGridMinSizeFlagDefaultIs15cm
--- PASS: TestGridMinSizeFlagDefaultIs15cm (0.00s)
=== RUN   TestHelpFlagIsParsed
--- PASS: TestHelpFlagIsParsed (0.00s)
=== RUN   TestHFlagIsParsed
--- PASS: TestHFlagIsParsed (0.00s)
=== RUN   TestHelpDefaultIsFalse
--- PASS: TestHelpDefaultIsFalse (0.00s)
=== RUN   TestRefineModeFlagIsParsed
--- PASS: TestRefineModeFlagIsParsed (0.00s)
=== RUN   TestRefineModeFlagDefaultIsAdd
--- PASS: TestRefineModeFlagDefaultIsAdd (0.00s)
PASS
ok      github.com/mfbonfigli/gocesiumtiler/test/unit   0.203s
```

Can you try the above and see if it helps?

**Comment by yadunandan6176** [comment]
Thank you for you response.

I was able to rectify it. May be the issue was `CGO_LDFLAGS="-g -02 -lm"` was not retained in `go env` after a try for build, hence build was failed. 

But when I set the same variable in the `go env` again and tried to build was successful with the warning as mentioned in the topic, I think we can ignore that as long as executable is generated and working.
