### ISSUE TITLE
Copc?

### ISSUE THREAD

**Issue by bertt** [mfbonfigli/gocesiumtiler#51]
Hi,

I'm trying to create 3D Tiles from copc from France site (in version 2.0.0-beta), but getting an error?

https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/KN/LHD_FXX_0659_6410_PTS_C_LAMB93_IGN69.copc.laz

 -epsg 2154

Error:

```

                           _                 _   _ _
  __ _  ___   ___ ___  ___(_)_   _ _ __ ___ | |_(_) | ___ _ __
 / _  |/ _ \ / __/ _ \/ __| | | | | '_   _ \| __| | |/ _ \ '__|
| (_| | (_) | (_|  __/\__ \ | |_| | | | | | | |_| | |  __/ |
 \__, |\___/ \___\___||___/_|\__,_|_| |_| |_|\__|_|_|\___|_|
  __| | A Cesium Point Cloud tile generator written in golang
 |___/  Copyright 2024 - Massimo Federico Bonfigli

*** Mode: File, process LAS file at LHD_FXX_0659_6410_PTS_C_LAMB93_IGN69.copc.laz
*** Execution settings:
- EPSG Code: 2154,
- Max Depth: 10,
- Resolution: 20.000000 meters,
- Min Points per tile: 5000
- Z-Offset: 0.000000 meters,
- Geoid elevation: false,
- 8Bit Color: false
- Join Clouds: false
- Tileset Version: 1.0

[2024-08-19 13:14:41.031] [LHD_FXX_0659_6410_PTS_C_LAMB93_IGN69.copc.laz] start reading las
[2024-08-19 13:14:41.033] [LHD_FXX_0659_6410_PTS_C_LAMB93_IGN69.copc.laz] las header read completed: found 40598265 points
[2024-08-19 13:14:41.034] [LHD_FXX_0659_6410_PTS_C_LAMB93_IGN69.copc.laz] point loading started
panic: runtime error: index out of range [134] with length 11

goroutine 52 [running]:
github.com/mfbonfigli/gocesiumtiler/v2/internal/las.(*FileLasReader).GetNext(0xc000072140)
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/internal/las/reader.go:179 +0x6f7
github.com/mfbonfigli/gocesiumtiler/v2/internal/las.(*CombinedFileLasReader).GetNext(0x0?)
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/internal/las/reader.go:127 +0xc5
github.com/mfbonfigli/gocesiumtiler/v2/internal/tree.(*GridTreeNode).loadPoints(0xc0001de000, {0x7ff6a4d05520, 0xc000072100}, {0x7ff6a4d054f0, 0xc0000080d8}, {0x7ff6a4d04a48, 0xc0000080f0}, {0x7ff6a4d05a68, 0xc000072080})
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/internal/tree/gridtree.go:427 +0x8c
github.com/mfbonfigli/gocesiumtiler/v2/internal/tree.(*GridTreeNode).Load(0x3?, {0x7ff6a4d05520?, 0xc000072100?}, {0x7ff6a4d054f0?, 0xc0000080d8?}, {0x7ff6a4d04a48?, 0xc0000080f0?}, {0x7ff6a4d05a68?, 0xc000072080?})
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/internal/tree/gridtree.go:85 +0x47
github.com/mfbonfigli/gocesiumtiler/v2.(*GoCesiumTiler).ProcessFiles(0xc0001cec00, {0xc000022160, 0x1, 0x1}, {0xc000010108, 0x17}, 0x86a, 0xc000076050, {0x7ff6a4d05a68, 0xc000072080})
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/tiler.go:116 +0x67e
main.fileCommand.func1({0x7ff6a4d05a68, 0xc000072080})
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/cmd/main.go:244 +0xdb
main.launch.func1()
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/cmd/main.go:276 +0x5c
created by main.launch in goroutine 1
        C:/Users/bonfi/go/src/github.com/mfbonfigli/gocesiumtiler/cmd/main.go:274 +0x105
```

Any idea? Maybe copc not supported or so?

**Comment by RZetko** [comment]
Use PDAL translate or other tool to decompress it to LAS file.

**Comment by mfbonfigli** [comment]
RZetko is correct, the application doesn't support LAZ (compressed LAS) files at the moment, so the files need to be converted to LAS first.

**Comment by reyemtm** [comment]
Run this command in pdal to convert to 1.3 and any other settings you may need - this also reprojects to Web Mercator so the file can be used in DeckGL. The `dataformat_id: 3` sets the output file to only have RGB and time, essentially cutting out all the point formats in v1.4/COPC.

```
convert.json
```

```Javascript
{
  "pipeline": [
    {
      "type": "readers.las",
      "filename": "input-copc.laz"
    },
    {
      "type": "filters.reprojection",
      "in_srs": "EPSG:4326",
      "out_srs": "EPSG:3857"
    },
    {
      "type": "writers.las",
      "filename": "output-v13.las",
      "minor_version": 3,
      "dataformat_id": 3,
      "discard_high_return_numbers": true
    }
  ]
}
```

```bash
pdal pipeline convert.json
```
